frontend/src/components/Header/index.tsx
frontend/src/components/SidebarPanel/index.tsx

This PR aligns the behavior with what's done on the main OpenTofu website, where header is static and only sidebars are sticky/floating. It's done mainly to simplify the logic that currently requires calculating the heights of the sidebar panels using the height of the header.
If we want, there's another approach that would allow sticky header with no funky heights for sidebars, but the main scrollbar would be moved inside the main column.

Make header static

---

frontend/src/components/Markdown/Pre.tsx

I've noticed some broken code blocks in MD of some providers which causes the page to crash. For context, GH's doesn't handle it either, it just displays an empty code block:
It seems like the auto-generation of CDKTF docs cannot handle code blocks in lists and nesting gets broken.

Handle broken code blocks in MD

---

frontend/src/components/Header/hooks/useGroupedResults.tsx

Seems like lunr.js doesn't have an easy/obvious way to disable the special characters in the search query. This PR disables 2 problematic ones and partially addresses #48

Filter out special chars from search query

---

frontend/src/components/RepoMetadataSidebarBlock/index.tsx
frontend/src/routes/Module/components/MetadataSidebarBlock.tsx
frontend/src/routes/Provider/components/MetadataSidebarBlock.tsx

Fixes #63
Preview: https://handle-missing-licence.registry-ui-dxi.pages.dev/module/hashicorp/terraform-cloud-operator/kubernetes/latest

Handle missing licence in UI

---

frontend/src/components/Markdown/H1.tsx
frontend/src/components/Markdown/H2.tsx
frontend/src/components/Markdown/H3.tsx
frontend/src/components/Markdown/Li.tsx
frontend/src/components/Markdown/Ol.tsx
frontend/src/components/Markdown/P.tsx
frontend/src/components/Markdown/Ul.tsx
frontend/src/routes/Provider/components/VersionInfo.tsx

Changelog:
- changed scroll margins on headings to match the horizontal padding of the container
- added top margin to the `<H1>` component that's reset to 0 if a heading is the first child in the container to avoid doubled space above it
- added margin resetting for `<H2>` and `<H3>`
- tweaked space between list elements to be half of the space between regular elements
- added small left padding to list elements to slightly separate bullets/numbers from the content
- increased line height in lists and paragraphs
- removed bottom margins from `<Ol>` and `<Ul>` lists, and made sure they have uniform top margins
- decreased top margins from lists inside list elements to match spacing between regular list items
- added top margin reset to any paragraph in a list element when it's the first …

Tweak spacings in MD content

---

frontend/src/components/VersionsSidebarBlock/index.tsx

When browsing latest version of modules we can close first version sections since currently active version (latest) is not listed there. This should make some room for submodules and examples in the module view.

Make sure correct version section is open by default

---

frontend/index.html

We can preload the fonts to have them available as early as possible.
| Before | After |
|-|-|
|![Screenshot 2024-08-23 at 23 33 29](https://github.com/user-attachments/assets/5427bb0c-b20d-4f3c-93d5-37a622e4b048)|![Screenshot 2024-08-23 at 23 32 28](https://github.com/user-attachments/assets/dd14db04-6161-49b9-ab12-64dde3801b03)|

Preload fonts

---

frontend/src/components/VersionsSidebarBlock/index.tsx

If you pick a version near or at the end of a version section you'll notice that there's only 3-4 versions total instead of the constant 5 (when possible). This PR adjusts the logic to show more versions before the active one whenever possible.
|Before|After|
|-|-|
|<video src="https://github.com/user-attachments/assets/cc119e86-854b-4bac-b5e0-c9a0d41435d9">|<video src="https://github.com/user-attachments/assets/a70c45ca-c302-4ef8-9618-6fe52574c1d4">|

Display more versions before the active one near the end of the list

---

search/worker/src/index.ts

The response returned from the cache is immutable, so attempting to attach additional headers throws an error. To resolve this, we need to create a fresh response based on the cached one and then set the CORS headers on it.

Clone cached response before applying CORS headers

---

frontend/package-lock.json
frontend/package.json
frontend/src/q.ts
frontend/src/query.ts
frontend/src/router.tsx
frontend/src/routes/Error/index.tsx
frontend/src/routes/Module/query.ts
frontend/src/routes/ModuleExample/query.ts
frontend/src/routes/ModuleSubmodule/query.ts
frontend/src/routes/Modules/query.ts
frontend/src/routes/Provider/query.ts
frontend/src/routes/Providers/query.ts
frontend/src/utils/errors.tsx

Fixes #96
I've used a small wrapper (`ky`) around `fetch` to unify HTTP response error handling. Whenever we receive a non-200 HTTP response, it throws an `HTTPError` that is caught by the error boundary around the routes. We can still display the 404 page by throwing a `NotFoundPageError`, for example, when requesting a non-existent submodule within an existing module's data.
I've also moved all routes under a route layout to use a single error boundary – I recommend [disabling whitespace](https://github.com/opentofu/registry-ui/pull/105/files?w=1) changes on the diff view.

Improve error handling in the UI

---

frontend/index.html

When you open the search bar the library we use (Headless UI) [sets right padding](https://github.com/tailwindlabs/headlessui/blob/2ff8458b0043f900bf6f8267f01385a6f7df2f04/packages/%40headlessui-react/src/hooks/document-overflow/adjust-scrollbar-padding.ts#L25) to offset the lack of scrollbar. Since we enforce stable scrollbar gutters we don't need the padding, otherwise we get doubled space.
|Before|After|
|-|-|
|<video src="https://github.com/user-attachments/assets/f4b1b146-d2ad-4998-abc1-3f680aa670be">|<video src="https://github.com/user-attachments/assets/4ca79626-b904-4b68-b526-8d7a3f6bb629">|

Disallow changing right padding

---

frontend/src/components/Markdown/P.tsx

This adds support for the custom admonition syntax that providers and modules may use in their docs to render special blocks with warnings/notes/etc. We could probably convert this into a remark/rehype plugin but this approach was quicker to implement.
We could also add support for the syntax that GH supports so that maintainers of providers and modules could render these blocks on both GH and our Registry UI in a unified way.
Closes #80

Handle custom admonition syntax

---

frontend/src/q.ts

By keeping previous results we avoid the blinking of the search dropdown which enables a bit smoother UX.

Keep previous search results while querying

---

frontend/src/components/Search/ModuleResult.tsx
frontend/src/components/Search/OtherResult.tsx
frontend/src/components/Search/ProviderResult.tsx

Some search results may have pretty long descriptions so to keep things in control let's clamp max lines to 3 which should be enough.

Clamp description of search results in the dropdown

---

frontend/src/components/Search/index.tsx

If the search dropdown renders below the search input it might look like it's cut. This PR adds a bit of padding between the dropdown and viewport to make clear that it has a correct height.

Add padding between search dropdown and viewport

---

backend/internal/license/license_detector.go

This PR adds a confidence override threshold for license scanning. If this threshold is met, all other detected licenses are ignored.

Adding a license confidence override threshold

---

frontend/src/routes/Module/components/ProvisionInstructionsSidebarBlock.tsx
frontend/src/routes/Provider/components/InstructionSidebarBlock.tsx

Fixed typo in module instructions

---

frontend/src/components/RepoSidebarBlock/index.tsx

Tweak how repo links are displayed

---

frontend/src/components/Footer/index.tsx
frontend/src/components/SidebarLayout/index.tsx
frontend/src/components/SimpleLayout/index.tsx
frontend/src/routes/Home/index.tsx

Addresses #165 and probably #88

Add footer

---

frontend/src/components/Markdown/P.tsx

Before: https://search.opentofu.org/provider/hashicorp/akamai/latest
After: https://reset-paragraphs-top-margin.registry-ui-dxi.pages.dev/provider/hashicorp/akamai/latest

Reset the top margin of paragraphs and admonitions if they are first elements in markdown content

---

frontend/src/components/ModuleInput/index.tsx
frontend/src/components/ModuleOutput/index.tsx

Use correct scroll margins for module input and output headings

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/LicenseSidebarBlock/index.tsx

The `groupBy` is still to new, so I've used `groupBy` from `es-toolkit` which is a smaller and faster alternative to `lodash`. 
This should fix #193

Use groupBy util to support older browsers

---

frontend/src/components/Markdown/P.tsx

The custom admonition syntax doesn't require a title/type so in that case we might be trimming whitespace that separates the first child and any JSX element that follows it. I've adjusted the logic to remove whitespace only if there's nothing left afterwards.
Here's an example of such admonition:
https://search.opentofu.org/provider/hashicorp/akamai/latest
And here's the preview of the fix:
https://do-not-trim-admonition-conte.registry-ui-dxi.pages.dev/provider/hashicorp/akamai/latest

Do not trim admonition content

---

frontend/src/routes/Provider/components/Error.tsx

Fixes #197
In cases where we don't have any provider version data we cannot use the data from the middleware. I've moved the logic into a component that'll run only when the data is available.
Preview:
https://521d63ef.registry-ui-dxi.pages.dev/provider/nonexistent/nonexistent/latest

Fix access to provider data in error boundary

---

frontend/src/routes/ModuleExample/Readme/index.tsx
frontend/src/routes/ModuleSubmodule/Readme/index.tsx

We have them in main module's readme as well as in provider details, but not in submodules and examples.

Add edit links to submodules and examples

---

backend/cmd/generate/main.go
backend/internal/backend.go
backend/internal/moduleindex/generator.go
backend/internal/providerindex/generator.go

Add namespacePrefix for more efficient population

---

.github/workflows/verify.yml
backend/internal/backend.go
backend/internal/blocklist/blocklist.go
backend/internal/indexstorage/bufferedstorage/index.go
backend/internal/providerindex/generator.go
backend/internal/providerindex/providerdocsource/scrape_test.go
backend/internal/providerindex/search.go
backend/internal/registrycloner/git.go

Closes #93
Adding golang linting for search/pg-indexer and backend folders:
After first run:
How it looks on the pipeline:
Fixes:

feat: add backend linting on github actions

---

.github/workflows/index-manual.yml
.github/workflows/index.yml
.github/workflows/verify.yml

Setup Go step on "Index (cron)" is not using the cache for the dependencies.

fix: github actions are not using dependencies cache

---

.github/workflows/index-manual.yml
.github/workflows/index.yml
.github/workflows/verify.yml

setup-action/cache doesn't working with working-directory as well. Reverting it back to full path to the binary.

fix: tofu binary cache doesn't work with working-directory

---

backend/internal/providerindex/generator.go

Fixes https://github.com/opentofu/registry-ui/issues/202
It's likely that having two codebases dealing with "what's a valid provider version" is a bad idea...
Example:
```
2025-03-03T10:42:01.6541185Z time=2025-03-03T10:41:59.212Z level=DEBUG-4 msg="Generating index for provider zhaochunqi/tencentcloud"
2025-03-03T10:42:01.7077130Z time=2025-03-03T10:41:59.237Z level=WARN msg="Invalid version number for provider zhaochunqi/tencentcloud: 1.61.8-alpha, skipping... (Invalid version: 1.61.8-alpha)" 
2025-03-03T10:42:01.7079092Z time=2025-03-03T10:41:59.237Z level=WARN msg="Invalid version number for provider zhaochunqi/tencentcloud: 1.61.10-alpha, skipping... (Invalid version: 1.61.10-alpha)"
2025-03-03T10:42:01.7080939Z time=2025-03-03T10:41:59.237Z level=WARN msg="Invalid version number for …
```

Filter out providers that don't have valid versions

---

search/worker/src/index.ts
search/worker/src/query.ts
search/worker/src/validation.ts

This also reformats the search query whitespace, it was annoying me.

added /top/providers query to allow you to query up tothe top 500 providers

---

frontend/src/components/ModuleInput/index.tsx

Previously we coerced the default value to a boolean to decide if we should show it. This resulted in false negatives for defaults of `null` and `""` (empty string).

Always show module optional input defaults

---

frontend/src/routes/Provider/components/DocsContent.tsx
frontend/src/routes/Provider/components/docsProcessor.test.ts
frontend/src/routes/Provider/components/docsProcessor.ts

Fixes #54, #279
Previously we had 2 issues.
- Anchor links from rendered markdown were not working correctly
- Relative links designed for the terraform registry were not working in the opentofu registry
This commit adds in a document pre-processor method that will take the markdown and convert the links to a friendlier format.
it will also ensure that any anchor links are correctly formatted to work with rehypeSanitizer.

Rework how links are rendered from markdown files

---

.github/workflows/remove-provider.yml
Makefile
backend/cmd/remove/main.go

- Add new remove command under backend/cmd/remove/ for removing providers
- Add GitHub Actions workflow for manual provider removal with dry-run option
- Add Makefile target 'remove-provider' for local usage
- Support removing specific versions or all versions of a provider

feat: add provider removal tool and GitHub workflow

---

frontend/src/routes/Provider/components/docsProcessor.test.ts
frontend/src/routes/Provider/components/docsProcessor.ts

Fixes https://github.com/opentofu/registry-ui/issues/342
OpenTofu provider documentation files can have [several different file extensions](https://github.com/opentofu/registry-ui/blob/main/documentation/documentation-sources.md#normalization-process).
The backend scraper handles the complete list of these extensions:
https://github.com/opentofu/registry-ui/blob/c4ea85ab9a4c077a31440f694991050daf8fe6ab/backend/internal/providerindex/providerdocsource/scrape.go#L241-L248
However, the frontend docs processor only handles `.html` and `.md`:
https://github.com/opentofu/registry-ui/blob/c4ea85ab9a4c077a31440f694991050daf8fe6ab/frontend/src/routes/Provider/components/docsProcessor.ts#L27-L30
As a result, extensions like `.html.markdown` are left in relative links in the files, resulting in …

Strip more Markdown file extensions
