- frontend/src/routes/Modules/components/CardItem.tsx
- frontend/src/routes/Modules/components/List.tsx
- frontend/src/routes/Modules/index.tsx
> Clean up modules list

- backend/internal/search/add.js
- backend/internal/search/searchtypes/index_item.go
- frontend/src/components/Header/Search.tsx
- frontend/src/components/Header/hooks/useGroupedResults.tsx
- frontend/src/components/Header/index.tsx
- frontend/src/icons/spinner.ts
- frontend/src/q.ts
This PR does the following:
- Hooks up the search bar in the top header
- Modifies how we generate the search index to include more data inside the ref
> Hook up search bar in header.

- frontend/index.html
- frontend/src/components/LanguagePicker/index.tsx
- frontend/src/components/VersionInfo/index.tsx
- frontend/src/routes/Provider/components/DocsContent.tsx
- frontend/src/routes/Provider/components/Header.tsx
- frontend/src/routes/Provider/components/VersionInfo.tsx
- frontend/src/routes/Provider/index.tsx
A few improvements to make the skeleton more stable and less jumpy.
> Improve skeleton of the provider page

- frontend/src/components/Header/Search.tsx
> Fix slash issue in the search input

- frontend/package-lock.json
- frontend/package.json
- frontend/src/routes/Provider/docsSidebar.test.ts
- frontend/src/routes/Provider/docsSidebar.ts
> When ordering known categories, place resources first

- frontend/src/components/MetadataSidebarBlock/index.tsx
- frontend/src/components/RepoMetadataSidebarBlock/index.tsx
| Before | After |
|-|-|
|![Screenshot 2024-08-23 at 18 15 53](https://github.com/user-attachments/assets/9b9413fb-870c-4bfb-833f-3fb5acbf1fef)|![Screenshot 2024-08-23 at 18 15 33](https://github.com/user-attachments/assets/4627e408-fb0c-41bd-8c10-547ce6d360a3)|
> Break metadata details into 2 lines

- frontend/src/components/VersionsSidebarBlock/index.tsx
- frontend/src/router.tsx
- frontend/src/routes/Provider/Docs/error.tsx
- frontend/src/routes/Provider/components/VersionsSidebarBlock.tsx
- frontend/src/routes/Provider/query.ts
Fixes #58
It can be improved, but we'll need to switch routers first.
> Persist version when navigating between docs pages

- .github/workflows/generate-manual.yml
- .github/workflows/generate.yml
- README.md
This PR adds a manual generation workflow. In addition, it limits the concurrent runs to 1.
> Manual generation workflow

- search/worker/src/index.ts
- search/worker/src/query.ts
- search/worker/wrangler.toml
This means now that we will also cache the search requests for 5 minutes.
I also added some logging so we can check the timings of US vs EU regions of neon.
> Move search and r2 caching up to the top level handler

- frontend/src/components/Search/index.tsx
- frontend/src/routes/Home/index.tsx
I've also added OpenTofu logo on the home page since it felt a bit empty before.
> Tweak home page styles

- frontend/src/components/Markdown/Hr.tsx
- frontend/src/components/Markdown/index.tsx
Example:
https://style-line-separators.registry-ui-dxi.pages.dev/provider/azure/azapi/latest
> Style line separators in MD

- frontend/src/components/LanguagePicker/index.tsx
- frontend/src/routes/Provider/components/VersionInfo.tsx
> Do not show CDKTF language switcher if there is nothing to switch

- backend/internal/indexstorage/api.go
- backend/internal/providerindex/providertypes/doc_item_name.go
> Adding @ to the allowed characters in paths

- frontend/src/components/RepoSidebarBlock/index.tsx
> Prevent the repo icon from shrinking

- frontend/src/components/Markdown/A.tsx
> Open markdown links in the same tab

- backend/internal/providerindex/generator.go
> Version fallback prefixed/non-prefixed

- frontend/src/components/Search/index.tsx
- frontend/src/hooks/useDebouncedValue.ts
- frontend/src/q.ts
I've also moved the debouncing into the Search component to completely skip the work.
> Increase search debounce delay and move debouncing logic

- frontend/src/routes/Provider/components/InstructionSidebarBlock.tsx
Fixes #206 
Signed-off-by: James Humphries <james@james-humphries.co.uk>## Checklist
> Fixed issue where name was used instead of namespace in instructions 

- frontend/src/router.tsx
The React Router's `unstable_dataStrategy` APIs was [changed](https://github.com/remix-run/react-router/pull/11943) in the last patch version, this PR adjusts our middleware logic to these changes.
> Update middleware logic

- backend/internal/moduleindex/generator.go
- backend/internal/moduleindex/module.go
- backend/internal/server/openapi.yml
> Stars and forks for modules

- backend/go.mod
- backend/go.sum
> Libregistry bump

- backend/internal/moduleindex/openapi.go
- backend/internal/providerindex/providerindexstorage/api.go
- backend/internal/search/searchstorage/openapi.go
- backend/internal/server/openapi.go
- backend/internal/server/openapi.yml
- search/pg-indexer/main.go
- search/worker/src/index.ts
> Changing the API root path

- frontend/docs/users/modules.md
> fix a typo: source -> module

- backend/internal/indexstorage/bufferedstorage/buffered.go
- backend/internal/indexstorage/bufferedstorage/buffered_test.go
> Fixing unnecessarily uploading unchanged files

- backend/internal/moduleindex/generator.go
- backend/internal/moduleindex/module.go
- backend/internal/providerindex/generator.go
- backend/internal/providerindex/providertypes/provider.go
This change attempts to fix #285 by only uploading the module/provider index when it has actually changed.
> Fixes #285: Unnecessary file upload

- search/worker/package-lock.json
- search/worker/package.json
Update Wrangler version in order to enable observability.
> update wrangler version

- .github/workflows/deploy-search-worker.yml
Resolves https://github.com/opentofu/registry-ui/issues/291
Checklist
[x] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
[x]  I have not used an AI coding assistant to create this PR.
[x]  My contribution is compatible with the MPL-2.0 license and I have provided a DCO sign-off on all my commits.
[x]  I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.
> feat: add deployment code for search/worker

- .github/workflows/index-manual.yml
- .github/workflows/index.yml
- .github/workflows/verify.yml
- frontend/src/components/DateTime/index.tsx
- frontend/src/components/Search/index.tsx
Fixes the action error introduced by the previous commit: 
https://github.com/opentofu/registry-ui/commit/71f7c5e19fc29dd746ab21f3222b31d43c059560
```
➜  registry-ui git:(main) ✗ actionlint
.github/workflows/index-manual.yml:42:28: "working-directory" is not available with "uses". it is only available with "run" [syntax-check]
|
42 |         working-directory: backend
|                            ^~~~~~~
.github/workflows/index.yml:21:28: "working-directory" is not available with "uses". it is only available with "run" [syntax-check]
|
21 |         working-directory: backend
|                            ^~~~~~~
.github/workflows/verify.yml:15:28: "working-directory" is not available with "uses". it is only available with "run" [syntax-check]
|
15 |         working-directory: backend
| …
```
> using right syntax for github actions

- frontend/src/routes/Providers/components/List.tsx
Resolves https://github.com/opentofu/registry-ui/issues/202
> fix: do not show provider if versions are null

- backend/internal/search/searchstorage/openapi.go
- backend/internal/server/openapi.yml
> Remove search.ndjson from the public API docs

- search/worker/src/query.ts
Exclude terraform-providers repos as they don't actually work anymore (will fix registry later) and downrank opentofu providers as well (just forks)
> Disable warnings due to registry changes and add excludes

- search/worker/src/query.ts
Submodules are not rendered or well handled in the registry UI currently.  This muddles the search results and produces a lot of useless "Other" category results.  A search for aws returns 1 module and 4 "submodules" that are not clickable
> Type rank modules above submodules

- documentation/documentation-sources.md
- documentation/license-detection.md
- documentation/search-worker.md
> Added initial documentation for some repo components/designs

- frontend/src/components/ModuleInput/index.tsx
* Format input names as bold, so they stand out
* Indent input description & defaults for a visual hierarchy
* Render markdown in input descriptions
> Improve module input formatting

- frontend/src/components/Markdown/index.tsx
> Trim the start of markdown documents to ensure that frontmatter processes correctly

- frontend/src/routes/Provider/components/DocsMenu.tsx
- frontend/src/routes/Provider/docsSidebar.test.ts
- frontend/src/routes/Provider/docsSidebar.ts
> 281: Add a filter to resources/datasources view

- backend/internal/moduleindex/generator.go
Fixes [#registry/2245](https://github.com/opentofu/registry/issues/2245)
The extractSubmodules and extractExamples functions had incorrect logic
for detecting whether "modules" or "examples" was a file vs directory.
The original code assumed that if workingCopy.Open() succeeded, it must
be a file, but Open() can succeed for both files and directories.
This caused all modules/examples directories to be incorrectly identified
as files and skipped during indexing, preventing submodules and examples
from being properly extracted and indexed.
This fixes that
> Fix broken scraping for examples and submodules

- backend/cmd/remove/main.go
There are situations where an item can end up in the search index but it cannot be found in the provider registry. 
An example of this is that when the initial search indexes were made, we included some providers that had a prefix of `terraform-provider` in their name. These need removing from the search index even though they do not exist as documentation anymore, or in the registry.
> Allow removal of items from only the search index

- backend/cmd/remove/main.go
> Also remove the item from the provider index

- frontend/docs/providers/docs.md
> docs(providers): Enhance front matter documentation
